# Generated by Django 3.1.4 on 2020-12-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='userscore',
            old_name='created',
            new_name='timestamp',
        ),
    ]
